import './style.css'
import './accessibility.css'
import './touch-targets.css'
import heroArt from './assets/lock-stack.webp'

const app=document.querySelector<HTMLDivElement>('#app')!
const nav='<header class="site-header"><a class="wordmark" href="/" aria-label="Migration Lock Rehearsal home">MLR<span>///</span></a><nav aria-label="Main navigation"><a href="/demo">Demo</a><a href="/#how">How it works</a><a href="/privacy">Privacy</a></nav></header>'
const footer='<footer><p>Rehearse database migrations before production.</p><p><a href="/privacy">Privacy</a> · <a href="/terms">Terms</a> · Built by Param Factory · v0.1.0</p></footer>'
const terminal='<section class="terminal" aria-labelledby="terminal-title"><div class="terminal-bar"><span></span><span></span><span></span><b id="terminal-title">DISPOSABLE RUN / postgres</b></div><pre tabindex="0" aria-label="Sample terminal output"><code><i>$</i> mlr demo --output ./mlr-demo\nstarting a fresh Postgres container\nloading invented fixture: 6 customers\nrunning add_customer_flag.sql\nstatement time: 184 ms\nlock wait: 0 ms\nrollback: checked\n<span class="go">VERDICT: GO</span>\nwrote ./mlr-demo/runbook.md<span class="cursor" aria-hidden="true">_</span></code></pre></section>'
function shell(content:string){return nav+'<main id="main" tabindex="-1">'+content+'</main>'+footer+'<div id="route-note" class="sr-only" aria-live="polite"></div>'}
function landing(){return shell('<section class="hero"><div><p class="eyebrow">MIGRATION PRE-FLIGHT / 0.1.0</p><h1>Rehearse your migration before production</h1><p class="lead">For database maintainers who need lock, rewrite, and rollback estimates before a release.</p><p class="action-row"><a class="button primary" href="/demo">Try it with sample data</a><span>See the bundled go/no-go card.</span></p><ul class="facts"><li>Fresh Docker container</li><li>Bundled invented sample</li><li>Reports use your output folder</li></ul></div><figure><img src="'+heroArt+'" width="1024" height="1024" fetchpriority="high" alt="A database cylinder held in an orange padlock with blue diagnostic tape."><figcaption>Measure the risk before the window opens.</figcaption></figure></section>'+terminal+'<section id="how" class="steps" aria-labelledby="how-title"><p class="eyebrow">THREE MOVES</p><h2 id="how-title">Run a migration rehearsal</h2><ol><li><b>Bring a fixture.</b><span>Use sanitized, production-shaped data.</span></li><li><b>Supply SQL.</b><span>Add the migration, rollback, and optional workload.</span></li><li><b>Read the card.</b><span>Get timings, table bytes, lock waits, and rollback status.</span></li></ol></section><section class="limits" aria-labelledby="limits-title"><h2 id="limits-title">What this tool does not do</h2><div><p>The rehearsal has no database URL option. It runs your SQL in the new container it creates. Results are estimates.</p><p>Start with <code>mlr demo</code>. It uses only the included fixture and writes a runbook.</p></div></section><section class="install" aria-labelledby="install-title"><h2 id="install-title">Install and rehearse</h2><pre><code>cargo run -- rehearse --fixture fixture.sql --migration change.sql --rollback down.sql --workload read.sql</code></pre><p>Docker must be running. The CLI creates a container and removes it after the run.</p></section>')}
function demo(){return shell('<section class="page-head"><p class="eyebrow">SAMPLE SANDBOX</p><h1>Read a sample migration card</h1><p class="lead">This preview uses invented customer records and does not save anything.</p><p class="action-row"><button class="button primary" id="reset-demo">Reset demo</button><a class="button" href="/">Start for real</a></p></section><aside class="demo-banner" role="status">Demo — sample data, nothing is saved</aside>'+terminal+'<section class="report" aria-labelledby="report-title"><h2 id="report-title">Go/no-go card</h2><dl><div><dt>Engine</dt><dd>Postgres 16</dd></div><div><dt>Statement time</dt><dd>184 ms</dd></div><div><dt>Lock wait</dt><dd>0 ms</dd></div><div><dt>Table bytes</dt><dd>32,768 → 40,960</dd></div><div><dt>Rollback</dt><dd>Checked</dd></div></dl><p><b>Estimate only.</b> Rehearse against a sanitized, production-shaped fixture before deployment.</p></section>')}
function legal(kind:'privacy'|'terms'){const p=kind==='privacy';return shell('<article class="legal"><p class="eyebrow">'+(p?'PRIVACY':'TERMS')+'</p><h1>'+ (p?'Privacy for a local migration tool':'Terms for Migration Lock Rehearsal')+'</h1><h2>'+(p?'No tracking or account data':'Use disposable data only')+'</h2><p>'+(p?'The documentation site makes only same-origin requests and stores no visitor data. The CLI runs the SQL files you name inside its new Docker container.':'Use this tool only with disposable databases and sanitized fixtures. Its measurements are estimates, not a guarantee of production behavior. Review its generated runbook before every deployment.')+'</p>'+(p?'<h2>Your reports stay local</h2><p>The CLI writes reports to the output folder you choose. Clear that folder when you no longer need a rehearsal card.</p>':'')+'</article>')}
function notFound(){return shell('<section class="page-head not-found"><p class="eyebrow">404 / ROUTE NOT FOUND</p><h1>Find the rehearsal page</h1><p class="lead">That address does not point to a migration card.</p><a class="button primary" href="/">Return home</a></section>')}
function route(moveFocus=false){const path=location.pathname.replace(/\/$/,'')||'/';app.innerHTML=path==='/demo'?demo():path==='/privacy'?legal('privacy'):path==='/terms'?legal('terms'):path==='/404'?notFound():path==='/'?landing():notFound();const titles:Record<string,string>={'/':'Migration Lock Rehearsal — Rehearse database migrations','/demo':'Demo — Migration Lock Rehearsal','/privacy':'Privacy — Migration Lock Rehearsal','/terms':'Terms — Migration Lock Rehearsal','/404':'Not found — Migration Lock Rehearsal'};document.title=titles[path]??titles['/404'];if(moveFocus){const heading=document.querySelector<HTMLElement>('h1')!;heading.tabIndex=-1;requestAnimationFrame(()=>heading.focus())}document.querySelector('#route-note')!.textContent=document.title;document.querySelector('#reset-demo')?.addEventListener('click',()=>{const b=document.querySelector<HTMLButtonElement>('#reset-demo')!;b.textContent='Demo reset';setTimeout(()=>b.textContent='Reset demo',1300)});document.querySelectorAll<HTMLAnchorElement>('a[href^="/"]').forEach(a=>a.addEventListener('click',e=>{if(e.metaKey||e.ctrlKey)return;e.preventDefault();history.pushState({},'',a.href);route(true)}))}
document.querySelector<HTMLAnchorElement>('.skip')?.addEventListener('click',event=>{event.preventDefault();const main=document.querySelector<HTMLElement>('#main')!;main.focus();main.scrollIntoView()})
addEventListener('popstate',()=>route(true));route()
