import './style.css'
import './paid.css'
import './accessibility.css'
import heroArt from './assets/lock-stack.webp'

const app=document.querySelector<HTMLDivElement>('#app')!
const licenseKey='sb_license:migration-lock-rehearsal'
const checkout='https://api.sociobot.in/api/v1/products/migration-lock-rehearsal/checkout'
const nav='<header class="site-header"><a class="wordmark" href="/" aria-label="Migration Lock Rehearsal home">MLR<span>///</span></a><nav aria-label="Main navigation"><a href="/demo">Demo</a><a href="/#how">How it works</a><a href="/privacy">Privacy</a></nav></header>'
const footer='<footer><p>Rehearse database migrations before production.</p><p><a href="/privacy">Privacy</a> · <a href="/terms">Terms</a> · Built by Param Factory · v0.1.0</p></footer>'
const terminal='<section class="terminal" aria-labelledby="terminal-title"><div class="terminal-bar"><span></span><span></span><span></span><b id="terminal-title">DISPOSABLE RUN / postgres</b></div><pre tabindex="0" aria-label="Sample terminal output"><code><i>$</i> mlr demo --output ./mlr-demo\nstarting a fresh Postgres container\nloading sanitized fixture: 6 customers\nrunning add_customer_flag.sql\nstatement time: 184 ms\nlock wait: 0 ms\nrollback: checked\n<span class="go">VERDICT: GO</span>\nwrote ./mlr-demo/runbook.md<span class="cursor" aria-hidden="true">_</span></code></pre></section>'
function shell(content:string){return nav+'<main id="main" tabindex="-1">'+content+'</main>'+footer+'<div id="route-note" class="sr-only" aria-live="polite"></div>'}
function landing(){return shell('<section class="hero"><div><p class="eyebrow">LOCAL-ONLY PRE-FLIGHT / 0.1.0</p><h1>Rehearse your migration before production</h1><p class="lead">For database maintainers who need lock, rewrite, and rollback estimates before a release.</p><p class="action-row"><a class="button primary" href="/demo">Try it with sample data</a><span>See the bundled go/no-go card.</span></p><ul class="facts"><li>Local Docker only</li><li>Sanitized sample included</li><li>One-time operator license</li></ul></div><figure><img src="'+heroArt+'" width="1024" height="1024" fetchpriority="high" alt="A database cylinder held in an orange padlock with blue diagnostic tape."><figcaption>Measure the risk before the window opens.</figcaption></figure></section>'+terminal+'<section id="how" class="steps" aria-labelledby="how-title"><p class="eyebrow">THREE MOVES</p><h2 id="how-title">Run a migration rehearsal</h2><ol><li><b>Bring a fixture.</b><span>Use sanitized, production-shaped data.</span></li><li><b>Supply SQL.</b><span>Add the migration, rollback, and optional workload.</span></li><li><b>Read the card.</b><span>Get timings, size movement, and rollback status.</span></li></ol></section><section class="limits" aria-labelledby="limits-title"><h2 id="limits-title">What this tool does not do</h2><div><p>It does not connect to production. It does not copy data. It does not author migrations. Results are estimates from a disposable environment.</p><p>Start with <code>mlr demo</code>. It uses only the included fixture and writes a runbook.</p></div></section><section class="install" aria-labelledby="install-title"><h2 id="install-title">Install and rehearse</h2><pre><code>cargo run -- rehearse --fixture fixture.sql --migration change.sql --rollback down.sql</code></pre><p>Docker must be running. The CLI creates a container and removes it after the run.</p></section><section class="paid" aria-labelledby="paid-title"><h2 id="paid-title">Keep the operator toolkit current</h2><p>$29 once. The operator license includes future engine checks. Reports, exports, and safety checks stay free.</p><p class="action-row"><a class="button primary" href="'+checkout+'">Buy operator license</a><span id="license-state" aria-live="polite">No license stored.</span></p><form id="restore-license"><label for="license-token">Have a license? Paste it.</label><input id="license-token" name="license" autocomplete="off"><button class="button" type="submit">Restore license</button></form></section>')}
function demo(){return shell('<section class="page-head"><p class="eyebrow">SAMPLE SANDBOX</p><h1>Read a sample migration card</h1><p class="lead">This preview uses invented customer records and does not save anything.</p><p class="action-row"><button class="button primary" id="reset-demo">Reset demo</button><a class="button" href="/">Start for real</a></p></section><aside class="demo-banner" role="status">Demo — sample data, nothing is saved</aside>'+terminal+'<section class="report" aria-labelledby="report-title"><h2 id="report-title">Go/no-go card</h2><dl><div><dt>Engine</dt><dd>Postgres 16</dd></div><div><dt>Statement time</dt><dd>184 ms</dd></div><div><dt>Lock wait</dt><dd>0 ms</dd></div><div><dt>Table bytes</dt><dd>32,768 → 40,960</dd></div><div><dt>Rollback</dt><dd>Checked</dd></div></dl><p><b>Estimate only.</b> Rehearse against a sanitized, production-shaped fixture before deployment.</p></section>')}
function legal(kind:'privacy'|'terms'){const p=kind==='privacy';return shell('<article class="legal"><p class="eyebrow">'+(p?'PRIVACY':'TERMS')+'</p><h1>'+ (p?'Privacy for a local migration tool':'Terms for Migration Lock Rehearsal')+'</h1><h2>'+(p?'No tracking or account data':'Use disposable data only')+'</h2><p>'+(p?'The documentation site makes no analytics or third-party requests. The CLI reads the SQL files you name and writes reports to the folder you choose. It does not send fixture data to us.':'Use this tool only with local or disposable databases and sanitized fixtures. Its measurements are estimates, not a guarantee of production behavior. Review its generated runbook before every deployment.')+'</p><h2>'+(p?'License storage':'License and support')+'</h2><p>'+(p?'If you buy an operator license, its token is stored in this browser and sent only to Sociobot to verify it. You can remove it by clearing this site’s browser storage.':'The operator license is a one-time $29 purchase. Sociobot and Dodo are the merchant of record. Refunds are handled there and revoke the license automatically.')+'</p></article>')}
function notFound(){return shell('<section class="page-head not-found"><p class="eyebrow">404 / ROUTE NOT FOUND</p><h1>Find the rehearsal page</h1><p class="lead">That address does not point to a migration card.</p><a class="button primary" href="/">Return home</a></section>')}
function setupLicense(){const param=new URLSearchParams(location.search).get('license');if(param){localStorage.setItem(licenseKey,param);history.replaceState({},'',location.pathname)}const note=document.querySelector<HTMLElement>('#license-state');const token=localStorage.getItem(licenseKey);if(!note||!token)return;if(localStorage.getItem(licenseKey+':checked')===new Date().toDateString()){note.textContent='License stored.';return}note.textContent='Checking license…';fetch('https://api.sociobot.in/api/v1/products/migration-lock-rehearsal/verify?license='+encodeURIComponent(token)).then(r=>r.json()).then(r=>{if(r.valid){localStorage.setItem(licenseKey+':checked',new Date().toDateString());note.textContent='License active.'}else{localStorage.removeItem(licenseKey);note.textContent='License no longer active. Buy a new license.'}}).catch(()=>note.textContent='License stored. It will be checked when online.');document.querySelector<HTMLFormElement>('#restore-license')?.addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector<HTMLInputElement>('#license-token')!;if(input.value.trim()){localStorage.setItem(licenseKey,input.value.trim());route()}})}
function route(){const path=location.pathname.replace(/\/$/,'')||'/';app.innerHTML=path==='/demo'?demo():path==='/privacy'?legal('privacy'):path==='/terms'?legal('terms'):path==='/404'?notFound():path==='/'?landing():notFound();const titles:Record<string,string>={'/':'Migration Lock Rehearsal — Rehearse database migrations','/demo':'Demo — Migration Lock Rehearsal','/privacy':'Privacy — Migration Lock Rehearsal','/terms':'Terms — Migration Lock Rehearsal','/404':'Not found — Migration Lock Rehearsal'};document.title=titles[path]??titles['/404'];requestAnimationFrame(()=>document.querySelector<HTMLElement>('h1')?.focus());document.querySelector('#route-note')!.textContent=document.title;document.querySelector('#reset-demo')?.addEventListener('click',()=>{const b=document.querySelector<HTMLButtonElement>('#reset-demo')!;b.textContent='Demo reset';setTimeout(()=>b.textContent='Reset demo',1300)});document.querySelectorAll<HTMLAnchorElement>('a[href^="/"]').forEach(a=>a.addEventListener('click',e=>{if(e.metaKey||e.ctrlKey)return;e.preventDefault();history.pushState({},'',a.href);route()}));setupLicense()}
addEventListener('popstate',route);route()
